homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path('', views.status, name='status'),
    path('about/', views.about, name='about'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=300)
    datetime = models.DateTimeField()

    def __str__(self):
        return self.status

homepage/views.py
from django.shortcuts import render
from .models import Status
import datetime

# Create your views here.

def about(request):
    return render(request,"about.html")

def status(request):
    list_of_status = Status.objects.all().order_by('datetime')
    if request.method == 'POST':
        user_status = request.POST.get('status')
        user_time = datetime.datetime.now()
        status = Status(status=user_status, datetime=user_time)
        status.save()
        return render(request, 'status.html', {'list_status' : list_of_status})

    else:
        return render(request, "status.html", {'list_status' : list_of_status})

homepage/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}JL | About Me{% endblock title %}

{% block content %}
<div class="container mt-5 pt-5">
    <div class="row text-center">
        <div class="col header" id="about">
            <img class="rounded-circle z-depth-2" width="250px" src="{% static 'image/profile.jpg' %}" data-holder-rendered="true">
            <h1 class="mt-3">Muhammad Jilham Luthfi</h1>
            <h2>Computer Science, Univesitas Indonesia | 2018</h2>
            <h2>
                I’m a highly motivated and hardworking person. Excellent in team working and always try to be a professional 
                at any possible time. I give someone chances to criticize my performance for the better.

                From a high school, my passion is technology. That's why I started learning in a computer science major. 
                I really hope someday I could make something helpful with my knowledge and spread education about how technology 
                can change our world.
            </h2>

            <div id="accordion">
                <div class="button" role="button">
                    Activities
                </div>
                <div class="slide">
                    <div class="mt-2 px-4 text-justify box">
                        <h4 class="title">Staff of Student Welfare Department</h4>
                        <p>
                            <strong>BEM Fasilkom UI 2018
                            <br> February 2019 - present</strong>
                            <br> 
                                I hold a project called "Peduli Maba" with my friend, <strong>Siti Nurfitriyah</strong>. The goal is 
                                to welcome the freshmen of Fasilkom UI 2019 by creating a group, holding an event called "Welcoming 
                                Maba", and managing our OA LINE to solve their problems.
                        </p>
                    </div>
                </div>
                <div class="button" role="button">
                    Organizations
                </div>
                <div class="slide">
                    <div class="mt-2 px-4 text-justify box">
                        <h4 class="title">BEM Fasilkom UI</h4>
                        <p>
                            <strong>Student's Advocacy and Welfare
                            <br> February 2019 - present</strong>
                            <br> 
                                Be a good friend of Fasilkom student by helping to solve their problems and accommodating aspirations
                                which will be forwarded to the faculty. We also managing the issues like academy, financial, and psychology
                                of Fasilkom student.
                        </p>
                    </div>
                </div>
                <div class="button" role="button">
                    Achievements
                </div>
                <div class="slide">
                    <div class="mt-2 px-4 text-justify box">
                        <h4 class="title">Pra OSP Ilmu Komputer 2016</h4>
                        <p>
                            <strong>February - March 2016</strong>
                            <br> 
                                A competition held by Dikdasmen Kemendikbud to find the best student in their own field. 
                                This competition attended by all the participants from elementary school to high school and 
                                undergo a series of selections until the final at the national stage. 
                        </p>
                    </div>
                </div>
                </div>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock title %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kreon&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">    


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/story7.js' %}" type="text/javascript"></script>

    <!-- Staticfiles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top py-0">
        <a class="navbar-brand header-title" href="#"><img src="{% static 'image/logo.png' %}" width="50" height="50" alt="">
            <span class="header-title">Jilham Luthfi</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
             
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:status' %}">Status <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:about' %}">About <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active dropdown header-subtitle">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Change Style
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a onclick="changeStyleSummerBreeze()" class="dropdown-item">Summer Breeze</a>
                      <a onclick="changeStyleMidnightSky()" class="dropdown-item">Midnight Sky</a>
                    </div>
                  </li>
            </ul>
        </div>    
    </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

homepage/templates/status.html
{% extends 'base.html' %}

{% block title %}JL | Live Status{% endblock title %}

{% block content %}
    <div class="container mt-5 pt-5" id="status">
        <div class="text-center">
            <h1>Hallo, wie geht's?</h1>
            <form id="form" method="POST">
                {% csrf_token %}
                <div class="form-group row justify-content-center">
                    <div class="col-6">
                        <input name="status" type="text" class="form-control" id="status-field" placeholder="Enter your status">
                    </div>
                </div>
                <button type="submit" class="btn">Submit</button>
            </form>
        </div>

        <div class="table-responsive my-5 px-4 py-2" id="status-table">
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col-2" class="header">No.</th>
                    <th scope="col-4" class="header">Status</th>
                    <th scope="col-4" class="header">Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for status in list_status %}
                    <tr id="content">
                        <td>{{forloop.counter}}</td>
                        <td>{{ status.status }}</td>
                        <td>{{ status.datetime }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}